name: matrix job
on: [ push ]
jobs:
  node-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [14, 15, 16]
    steps:
      - name: print the node versions
        run: echo ${{ matrix.node_version }}
  
