name: re usable workflow
on:
  workflow_call:
    inputs:
      name:
        description: "enter your name"
        type: string
        required: true
    outputs:
      date: 
        value: ${{ jobs.called-workflow.outputs.date }}

jobs:
  called-workflow:
    runs-on: ubuntu_latest
    outputs:
      date: ${{ steps.step-1.outputs.date}}
    steps:
      - name: desiplay name
        run: echo ${{inputs.name}}
      - name: todays date
        run: date=$(date) >> $GITHUB_OUTPUT
        id: step-1
